### ISSUE TITLE
Starting image off to the side

### ISSUE THREAD

**Issue by ZebGirouard** [alexi-o/whack-a-trump#4]
Before game starts, the welcome image is off to the side, so it obscures the Player 1/Player 2 div, and allows user to see left side of game:

<img width="847" alt="screen shot 2017-04-01 at 2 28 48 pm" src="https://cloud.githubusercontent.com/assets/5480464/24582196/b02a64ac-16e7-11e7-8c9d-d5cbd59de388.png">

**Comment by alexi-o** [comment]
Problem solved! I moved the gameTitle div inside of the gameContainer div and now it aligns correctly.
